# Syntax Version
version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./requirements/nginx/Dockerfile
        container_name: nginx-container
        depends_on:
           - wordpress
        ports:
            - "443:443"
        networks:
           - inception-network

        volumes:
            -  nginx-wp-volume:/var/www/wordpress
            - ./requirements/nginx/tools/:/etc/nginx/ssl/
            - ./requirements/nginx/conf/:/etc/nginx/http.d/
    mariadb:
        build:
          context: .
          dockerfile: ./requirements/mariadb/Dockerfile
          args:
            DB_NAME:            ${DB_NAME}
            DB_USER_PASS:       ${DB_USER_PASS}
            DB_USER_NAME:       ${DB_USER_NAME}
            DB_ROOT:            ${DB_ROOT}
            DB_ROOT_PASS:       ${DB_ROOT_PASS}
            DB_MYSQL:           ${DB_MYSQL}
            DB_MYSQL_PASS:      ${DB_MYSQL_PASS}
        container_name: mariadb
        ports:
          - "3306:3306"
        networks:
          - inception-network
        volumes:
          - mariadb-volume:/var/lib/mysql/

        restart: always
    
    wordpress:
      build:
        context: .
        dockerfile: ./requirements/wordpress/Dockerfile
        args:
            DB_NAME:            ${DB_NAME}
            DB_USER_NAME:       ${DB_USER_NAME}
            DB_USER_PASS:       ${DB_USER_PASS}
      container_name: wordpress
      depends_on: 
        - mariadb
      restart: always
      networks:
        - inception-network
      volumes:
            - nginx-wp-volume:/var/www/wordpress/
        
volumes:
  mariadb-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/mariadb

  nginx-wp-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress
  
networks:
  inception-network:
    driver: bridge
