# Syntax Version
version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./requirements/nginx/Dockerfile
        container_name: nginx-container
#       depends_on:
#           - wordpress
        ports:
            - "443:443"
        volumes:
            -  /home/adriouic/Inception_42/simple_docker_nginx_html/public/html/:/var/www/
            - ./requirements/nginx/tools/:/etc/nginx/ssl/
            - ./requirements/nginx/conf/:/etc/nginx/http.d/
    mariadb:
        build:
          context: .
          dockerfile: ./requirements/mariadb/Dockerfile
        container_name: mariadb
        ports:
          - "3306:3306"
        restart: always
