# Syntax Version
version: '3'

services:
    nginx:
        build:
            contex: .
            dockerfile: ./requirements/nginx/Dockerfile
        container_name: nginx-container
#       depends_on:
#           - wordpress
        ports:
            - "443:443"

