# Syntax Version
version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./requirements/nginx/Dockerfile
        container_name: nginx-container
#       depends_on:
#           - wordpress
        ports:
            - "443:443"
        volumes:
            - ./requirements/nginx/tools/:/etc/nginx/ssl/
            - ./requirements/nginx/conf/:/etc/nginx/http.d/
            - /home/adriouic/Desktop/simple_docker_nginx_html/public/html:/var/www/public/html/

